---
version: '3.8'
services:
  kyria:
    image: zmk_dev:miryoku_zmk
    build: .
    environment:
      - "ZEPHYR_TOOLCHAIN_VARIANT=cross-compile"
      - "CROSS_COMPILE=/usr/bin/arm-none-eabi-"
    volumes:
      - type: bind
        source: ./
        target: /miryoku_zmk
        read_only: true
      - type: bind
        source: ./build/left.uf2
        target: /zmk/app/build/left/zephyr/zmk.uf2
        read_only: false
      - type: bind
        source: ./build/right.uf2
        target: /zmk/app/build/right/zephyr/zmk.uf2
        read_only: false
    command:
      - /bin/sh
      - -c 
      - |
        /usr/local/bin/west build -d build/right -p -b nice_nano_v2 -- -DSHIELD="kyria_rev2_right nice_view_adapter nice_view" -DZMK_CONFIG="/miryoku_zmk/config/"
        /usr/local/bin/west build -d build/left  -p -b nice_nano_v2 -- -DSHIELD="kyria_rev2_left nice_view_adapter nice_view" -DZMK_CONFIG="/miryoku_zmk/config/"
  kyria_prestine:
    image: zmk_dev:miryoku_zmk
    build: .
    environment:
      - "ZEPHYR_TOOLCHAIN_VARIANT=cross-compile"
      - "CROSS_COMPILE=/usr/bin/arm-none-eabi-"
    volumes:
      - type: bind
        source: ./
        target: /miryoku_zmk
        read_only: true
      - type: bind
        source: ./build/left.uf2
        target: /zmk/app/build/left/zephyr/zmk.uf2
        read_only: false
      - type: bind
        source: ./build/right.uf2
        target: /zmk/app/build/right/zephyr/zmk.uf2
        read_only: false
    command:
      - /bin/sh
      - -c 
      - |
        /usr/local/bin/west build -p -d build/right -b nice_nano_v2 -- -DSHIELD="kyria_rev2_right nice_view_adapter nice_view" -DZMK_CONFIG="/miryoku_zmk/config/"
        /usr/local/bin/west build -p -d build/left -b nice_nano_v2 -- -DSHIELD="kyria_rev2_left nice_view_adapter nice_view" -DZMK_CONFIG="/miryoku_zmk/config/"
  reset:
    image: zmk_dev:miryoku_zmk
    build: .
    environment:
      - "ZEPHYR_TOOLCHAIN_VARIANT=cross-compile"
      - "CROSS_COMPILE=/usr/bin/arm-none-eabi-"
    volumes:
      - type: bind
        source: ./
        target: /miryoku_zmk
        read_only: true
      - type: bind
        source: ./build/reset.uf2
        target: /zmk/app/build/reset/zephyr/zmk.uf2
        read_only: false
    command:
      - /bin/sh
      - -c 
      - |
        /usr/local/bin/west build -p -d build/reset -b nice_nano_v2 -- -DSHIELD="settings_reset" -DZMK_CONFIG="/miryoku_zmk/config/"

